### ISSUE TITLE
Pairing offset works without a partner (+ Several server chat issues)

### ISSUE THREAD

**Issue by MisthalinMystery** [Enovale/Alibi#1]
Some of these may have been resolved already, though I am listing them just in case. All of them were tested with Web, though some are confirmed to show on Client.

-----

- If you select a partner and choose an offset, it will function as if you have a partner and move your character accordingly.

- 8ball has no character limit and has no message length limit.

- Rolling privately sends nothing back to the server chat. (/rollp)

**Comment by Enovale** [comment]
All issues fixed in https://github.com/ElijahZAwesome/Alibi/commit/bb433638777a505aa9756d481c9ef84799fd1603
